name: JaredGardner
favicon: null
layout_spectrum: 0.99359
typography_spectrum: 0.28896
title: Jared Gardner
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#80807b'
    - '#565759'
    - '#2f2e32'
    - '#fdfdfd'
    - '#a8b1aa'
  brandStrength: 0.5
  lightness: 0.5767319337464869
  saturation: 0.4420623092446476
  rhythmicContrast: 0.6878202359657735
purpose: []
