name: JaredGardner
favicon: null
layout_spectrum: 0.74516
typography_spectrum: 0.50432
title: Jared Gardner
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#80807b'
    - '#565759'
    - '#2f2e32'
    - '#fdfdfd'
    - '#a8b1aa'
  brandStrength: 0.3125
  lightness: 0.6875
  saturation: 0
  rhythmicContrast: 1
purpose: []
